name: DevOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Code
      run: |
        pip install flake8
        flake8 . --ignore=E501

    - name: Build Docker Image
      run: |
        docker build -t flask-app:latest .

    - name: Run Docker Container
      run: |
        docker run -d -p 5000:5000 flask-app:latest
